# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: make build dir
        run: mkdir build && brew install neofetch && neofetch && ls -l /usr/local/bin && /usr/local/bin/gcc-11 -v  && /usr/local/bin/g++-11 -v && lz4 --version && ls -l /usr/lib/jdk1.3.1/bin

#       - name: pwd
#         run: pwd
        
      - name: build vlc
        run: cd build && pwd && ../extras/package/macosx/build.sh -i n -a x86_64 
      # Runs a set of commands using the runners shell
#       - name: build script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
